//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerStats.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_SoccerStatsEntities : DbContext
    {
        public BD_SoccerStatsEntities()
            : base("name=BD_SoccerStatsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Championnat> T_Championnat { get; set; }
        public virtual DbSet<T_Club> T_Club { get; set; }
        public virtual DbSet<T_Competition> T_Competition { get; set; }
        public virtual DbSet<T_Entraineur> T_Entraineur { get; set; }
        public virtual DbSet<T_Joueur> T_Joueur { get; set; }
        public virtual DbSet<T_Resultat> T_Resultat { get; set; }
        public virtual DbSet<T_Stats> T_Stats { get; set; }
    }
}
