//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Club()
        {
            this.T_Entraineur = new HashSet<T_Entraineur>();
            this.T_Joueur = new HashSet<T_Joueur>();
            this.T_Resultat = new HashSet<T_Resultat>();
        }
    
        public int idClub { get; set; }
        public int idChampionnat { get; set; }
        public string nomClub { get; set; }
    
        public virtual T_Championnat T_Championnat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Entraineur> T_Entraineur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Joueur> T_Joueur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Resultat> T_Resultat { get; set; }
    }
}
