//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Joueur
    {
        public int idJoueur { get; set; }
        public int idStats { get; set; }
        public int idClub { get; set; }
        public string nomJoueur { get; set; }
        public string prenomJoueur { get; set; }
        public int ageJoueur { get; set; }
        public int poidsJoueurKg { get; set; }
        public int tailleJoueurCm { get; set; }
        public string nationaliteJoueur { get; set; }
    
        public virtual T_Club T_Club { get; set; }
        public virtual T_Stats T_Stats { get; set; }
    }
}
