//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Resultat
    {
        public int idResultat { get; set; }
        public int idClub { get; set; }
        public int idCompetition { get; set; }
        public string clubDomicile { get; set; }
        public string clubExterieur { get; set; }
        public int scoreDomicile { get; set; }
        public int scoreExterieur { get; set; }
        public bool victoireDomicile { get; set; }
        public bool victoireExterieur { get; set; }
    
        public virtual T_Club T_Club { get; set; }
        public virtual T_Competition T_Competition { get; set; }
    }
}
